"""
This type stub file was generated by pyright.
"""

class Graph:
    def get_shortest_path(self, id: int, to: int | None = ..., output: str = ...) -> list[int]:
        ...
    
    def __init__(self, n: int, edges: list[tuple[int, int]]) -> None:
        ...
    


