services:
  wirecraft-server:
    hostname: wirecraft-server
    init: true
    environment:
      - DATABASE=data/database.db
    build:
      context: .
      target: production
    ports:
      - 8765:8765
    volumes:
      - $PWD/data:/app/data
