name: wirecraft

services:
  wirecraft-server:
    hostname: wirecraft-server
    init: true
    environment:
      # Change this locally accordingly to the database environment, or use variable interpolation from a local .env
      DATABASE: "admin:projetinfo1A@postgres/wirecraft"
      DATABASE_TYPE: "postgresql"
    build:
      context: .
      target: production
    image: ghcr.io/wirecraft-team/wirecraft:main
    ports:
      - 8765:8765
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "websocat", "ws://127.0.0.1:8765/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  database:
    hostname: postgres
    image: postgres:17.5-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=wirecraft
      # when in production, swap this locally
      - POSTGRES_PASSWORD=projetinfo1A
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 1m
