name: Check for style, typing, etc...

on:
  push:
  pull_request:

jobs:
  check:
    name: Execute test, check style, lint...
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install tox
        run: uv sync --only-group tox --frozen --python 3.13
      # - name: Execute tox  # TODO(airopi): réparer
      #   run: uv run tox
